name: Livro de Visitas
description: Deixe uma mensagem legal para mim!
labels: ["livro-de-visitas"]
body:
  - type: input
    id: nome
    attributes:
      label: Seu nome
      placeholder: "Digite seu nome aqui"
    validations:
      required: true
  - type: textarea
    id: mensagem
    attributes:
      label: Mensagem
      placeholder: "Encontrei seu perfil através de:
      
<!-- Me conte como você me encontrou -->

Mensagem:

<!-- Escreva sua mensagem aqui -->"

    validations:
      required: true
