name: Livro de Visitas
description: Deixe uma mensagem legal para mim!
title: "[Livro de Visitas]"
labels: ["livro-de-visitas"]
body:
  - type: input
    id: nome
    attributes:
      label: Seu nome
      placeholder: "Digite seu nome aqui"
    validations:
      required: true
  - type: textarea
    id: mensagem
    attributes:
      label: Mensagem
      placeholder: "Deixe sua mensagem aqui"
    validations:
      required: true
