name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Sao_Paulo
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: no
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
